
service: python-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1  
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            [
              !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/python_serverless'
            ]
functions:
  postData:
    handler: handler.postData
    events:
      - http:
          path: post/demo
          method: post
          cors: true

  getData:
    handler: handler.getData
    events:
      - http:
          path: show/{id}
          method: get
          cors: true

  updateData:
    handler: handler.updateData
    events:
      - http:
          path: update/{id}
          method: put
          cors: true

  deleteData:
    handler: handler.deleteData
    events:
      - http:
          path: delete/{id}
          method: delete
          cors: true

resources:
  Resources:
    DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "id"
            KeyType: HASH
          -
            AttributeName: "id"
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: python_serverless         
